CREATE DATABASE GestaoEscolar;
GO
USE GestaoEscolar;
GO
CREATE TABLE ALUNO (
    id INT IDENTITY(1,1) CONSTRAINT PK_ALUNO PRIMARY KEY,
    matricula NVARCHAR(20) CONSTRAINT UQ_ALUNO_MATRICULA UNIQUE NOT NULL,
    nome NVARCHAR(100) NOT NULL,
    data_nascimento DATE NOT NULL
);
GO

CREATE TABLE DOCENTE (
    id INT IDENTITY(1,1) CONSTRAINT PK_DOCENTE PRIMARY KEY,
    registro NVARCHAR(20) CONSTRAINT UQ_DOCENTE_REGISTRO UNIQUE NOT NULL,
    nome NVARCHAR(100) NOT NULL,
    especialidade NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE CURSO (
    id INT IDENTITY(1,1) CONSTRAINT PK_CURSO PRIMARY KEY,
    nome NVARCHAR(100) NOT NULL,
    descricao NVARCHAR(MAX) NULL,
    carga_horaria INT NOT NULL
);
GO
CREATE TABLE TURMA (
    id INT IDENTITY(1,1) CONSTRAINT PK_TURMA PRIMARY KEY,
    ano_semestre NVARCHAR(10) NOT NULL,
    curso_id INT NOT NULL,
    docente_id INT NOT NULL,
    CONSTRAINT FK_TURMA_CURSO FOREIGN KEY (curso_id) REFERENCES CURSO(id),
    CONSTRAINT FK_TURMA_DOCENTE FOREIGN KEY (docente_id) REFERENCES DOCENTE(id)
);
GO
CREATE TABLE ALUNO_TURMA (
    aluno_id INT NOT NULL,
    turma_id INT NOT NULL,
    data_matricula DATE CONSTRAINT DF_ALUNO_TURMA_DATA DEFAULT GETDATE(),
    nota DECIMAL(5,2) NULL, 
    faltas INT CONSTRAINT DF_ALUNO_TURMA_FALTAS DEFAULT 0,
    CONSTRAINT PK_ALUNO_TURMA PRIMARY KEY (aluno_id, turma_id),
    CONSTRAINT FK_ALUNO_TURMA_ALUNO FOREIGN KEY (aluno_id) REFERENCES ALUNO(id),
    CONSTRAINT FK_ALUNO_TURMA_TURMA FOREIGN KEY (turma_id) REFERENCES TURMA(id)
);
GO
CREATE NONCLUSTERED INDEX IX_TURMA_CURSO_ID ON TURMA(curso_id);
GO
CREATE NONCLUSTERED INDEX IX_TURMA_DOCENTE_ID ON TURMA(docente_id);
GO
CREATE NONCLUSTERED INDEX IX_ALUNO_TURMA_TURMA_ID ON ALUNO_TURMA(turma_id);
GO